In [1]:
import numpy as np

In [3]:
a = np.ones((2, 3))
print(a)
b= np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [6]:
# find the determinant
c= np.identity(3)
np.linalg.det(c)

1.0

## Reorganizing Arrays

In [13]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
print(before)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [8]:
after = before.reshape((8,1))

In [9]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [11]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Vertically stacking vectors

In [15]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [16]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Horizontal Stack

In [19]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [20]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])