# Numpy Arrays

In [133]:
import sys
import numpy as np

In [135]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [136]:
a = np.array([1, 2, 3, 4, 5])

In [137]:
b = np.array([0, -6.5, 3, 5, 7.2])

In [138]:
a[0], a[3]

(1, 4)

In [139]:
b[0:]

array([ 0. , -6.5,  3. ,  5. ,  7.2])

In [140]:
a[1:3]

array([2, 3])

In [141]:
b[0], b[-1]

(0.0, 7.2)

In [142]:
b[[0, 2, -1]]

array([0. , 3. , 7.2])

## Array Types

In [143]:
a.dtype

dtype('int32')

In [144]:
b.dtype

dtype('float64')

In [145]:
np.array([1, 2, 3, 4], dtype=np.float64)
# float sadece yazında olmuyor.

array([1., 2., 3., 4.])

In [146]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [147]:
c = np.array(['a', 'b', 'c'])

In [148]:
c.dtype

dtype('<U1')

In [149]:
d = np.array([{'a': 1}, sys])

In [150]:
d.dtype

dtype('O')

## Dimensions and Shapes

In [151]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [152]:
A.shape

(2, 3)

In [153]:
A.ndim # dimesion

2

In [154]:
A.size # total num of elements

6

In [155]:
bb = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [156]:
bb

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [157]:
bb.shape 

(2, 2, 3)

In [158]:
bb.size

12

In [159]:
cc = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [160]:
cc.dtype # object

NameError: name 'cc' is not defined

## Indexing and Slicing of Matrices

In [161]:
# Square matrix
sm = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [162]:
sm[1]

array([4, 5, 6])

In [163]:
# sm[d1, d2, d3, d4]

In [164]:
sm[1][0]

4

In [165]:
sm[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
sm[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [167]:
sm[:2,:2]

array([[1, 2],
       [4, 5]])

In [168]:
sm[:2,2:]

array([[3],
       [6]])

In [169]:
sm[1] = np.array([10, 10, 10])

In [170]:
sm

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [171]:
sm[2] = 99

In [172]:
sm

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary Statistics

In [173]:
a = np.array([1, 2, 3, 4])

In [174]:
a.sum()

10

In [175]:
a.mean()

2.5

In [176]:
a.std()

1.118033988749895

In [177]:
a.var()

1.25

In [178]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [179]:
A.sum()

45

In [180]:
A.mean()

5.0

In [181]:
A.std()

2.581988897471611

In [182]:
A.sum(axis=0)

array([12, 15, 18])

In [183]:
A.sum(axis=1)

array([ 6, 15, 24])

In [184]:
A.mean(axis=0)

array([4., 5., 6.])

In [185]:
# hepsinin exis 0 ve 1de değerleri vardır

## Broadcasting and Vectorized Operations,

In [186]:
a = np.arange(4)

In [187]:
a

array([0, 1, 2, 3])

In [188]:
a +10

array([10, 11, 12, 13])

In [189]:
a

array([0, 1, 2, 3])

In [190]:
a*10

array([ 0, 10, 20, 30])

In [191]:
l = [0, 1, 2, 3]

In [192]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [193]:
b = np.array([10, 10, 10, 10])

In [194]:
a+b

array([10, 11, 12, 13])

In [195]:
a * b

array([ 0, 10, 20, 30])

## Boolean Arrays

In [196]:
a = np.arange(4)

In [201]:
a

array([0, 1, 2, 3])

In [197]:
a[[0, -1]]

array([0, 3])

In [205]:
a[[True, False, True, False]] # istediğimiz elemanları yazdırma

array([0, 2])

In [204]:
a[False]

array([], shape=(0, 4), dtype=int32)

In [206]:
a >= 2

array([False, False,  True,  True])

In [207]:
a[a>=2]

array([2, 3])

In [208]:
a[~(a > a.mean())] # not demek

array([0, 1])

In [209]:
a[(a==0) | (a == 1)]

array([0, 1])

In [210]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [211]:
A = np.random.randint(100, size=(3, 3))

In [212]:
A

array([[84, 47, 88],
       [ 8,  5, 18],
       [ 8, 90, 39]])

In [213]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([84, 88,  5,  8, 39])

In [214]:
A>30

array([[ True,  True,  True],
       [False, False, False],
       [False,  True,  True]])

In [215]:
A[A > 30]

array([84, 47, 88, 90, 39])

## Linear Algebra

In [216]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [217]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [218]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [219]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [220]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [221]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [222]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

### Int, float

In [224]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [225]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [226]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [227]:
np.dtype(float).itemsize

8

### lists are even larger

In [228]:
sys.getsizeof([1])

64

In [229]:
np.array([1]).nbytes

4

### And performance is also important

In [230]:
l = list(range(1000))

In [231]:
a = np.arange(1000)

In [232]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 15.9 ms


332833500

In [235]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 0 ns


332833500

## Useful Numpy Functions

### Random

In [236]:
np.random.random(size=2)

array([0.44285152, 0.04605547])

In [237]:
np.random.normal(size=2)

array([ 0.64164163, -1.23709017])

In [238]:
np.random.rand(2,4)

array([[0.29495692, 0.16170533, 0.4195603 , 0.35899419],
       [0.90640188, 0.93129565, 0.99674569, 0.26645194]])

### Arange

In [239]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [240]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [241]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### Reshape 

In [242]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [243]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Linspace 

In [244]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [245]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [246]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### Zeros, ones, empty

In [248]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [250]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [253]:
np.zeros((3, 3), dtype=np.int) # anlamadım

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [254]:
np.ones(3)

array([1., 1., 1.])

In [255]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [257]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### Identity and eye

In [258]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [259]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [260]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [261]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [262]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [263]:
"Hello world"[6]

'w'